myflaskapp/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, abort, flash, current_app
from flask_login import login_user, logout_user, login_required, current_user
from .models import User, Article
from .forms import SubmitArticleForm, RegistrationForm, UpdateProfileForm, SearchForm
from . import db
from werkzeug.utils import secure_filename
import os
from .forms import SettingsForm
from flask import jsonify


routes = Blueprint('routes', __name__)

@routes.route('/')
def home():
    return render_template('home.html')

@routes.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('routes.home'))
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        remember = request.form.get('remember')
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user, remember=remember)
            return redirect(url_for('routes.home'))
    return render_template('login.html')

@routes.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.home'))

@routes.route('/articles/<int:article_id>', methods=['GET'])
def get_article(article_id):
    article = Article.query.get(article_id)
    if article is None:
        abort(404, description="Article not found")
    return render_template('article.html', article=article)

@routes.route('/articles')
def articles():
    articles = Article.query.all()
    return render_template('articles.html', articles=articles)

@routes.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('routes.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('routes.login'))
    return render_template('register.html', title='Register', form=form)

@routes.route('/profile/update', methods=['GET', 'POST'])
@login_required
def update_profile():
    form = UpdateProfileForm()

    if form.validate_on_submit():
        current_user.bio = form.bio.data

        if form.profile_picture.data:
            filename = secure_filename(form.profile_picture.data.filename)
            form.profile_picture.data.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            current_user.profile_picture = filename

        db.session.commit()
        flash('Your profile has been updated!', 'success')
        return redirect(url_for('routes.profile'))

    form.bio.data = current_user.bio

    return render_template('update_profile.html', title='Update Profile', form=form)

@routes.route('/profile')
@login_required
def profile():
    return render_template('profile.html', user=current_user)

@routes.route('/about')
def about():
    return render_template('about.html')

@routes.route('/contact')
def contact():
    return render_template('contact.html')

@routes.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@routes.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

@routes.route('/submit_article', methods=['GET', 'POST'])
@login_required
def submit_article():
    form = SubmitArticleForm()
    if form.validate_on_submit():
        new_article = Article(
            title=form.title.data,
            link=form.link.data,
            description=form.description.data,
            category=form.category.data
        )

        db.session.add(new_article)
        db.session.commit()
        return redirect(url_for('routes.home'))
    return render_template('submit_article.html', form=form)

@routes.route('/edit_article/<int:article_id>', methods=['GET', 'POST'])
@login_required
def edit_article(article_id):
    article = Article.query.get_or_404(article_id)

    if article.author != current_user:
        abort(403)  # Forbidden access

    form = SubmitArticleForm()

    if form.validate_on_submit():
        article.title = form.title.data
        article.link = form.link.data
        article.description = form.description.data
        article.category = form.category.data

        db.session.commit()
        flash('Article has been updated!', 'success')
        return redirect(url_for('routes.articles'))

    # Pre-fill the form fields with the existing article data
    form.title.data = article.title
    form.link.data = article.link
    form.description.data = article.description
    form.category.data = article.category

    return render_template('edit_article.html', title='Edit Article', form=form)


@routes.route('/delete_article/<int:article_id>', methods=['POST'])
@login_required
def delete_article(article_id):
    article = Article.query.get_or_404(article_id)

    if article.author != current_user:
        abort(403)  # Forbidden access

    db.session.delete(article)
    db.session.commit()
    flash('Article has been deleted!', 'success')
    return redirect(url_for('routes.articles'))


@routes.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()

    if form.validate_on_submit():
        search_query = form.search_query.data

        # Perform the search query on your database
        search_results = perform_search(search_query)

        return render_template('search.html', form=form, search_results=search_results, user=current_user)

    return render_template('search.html', form=form, user=current_user)

def perform_search(search_query):
    # Perform the necessary database query to retrieve search results
    # based on the search query
    search_results = Article.query.filter(Article.title.ilike(f"%{search_query}%")).all()
    return search_results


@routes.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingsForm()

    if form.validate_on_submit():
        # Update the user's settings in the database
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.set_password(form.new_password.data)
        current_user.bio = form.bio.data

        if form.profile_picture.data:
            # Save the uploaded profile picture
            filename = secure_filename(form.profile_picture.data.filename)
            form.profile_picture.data.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            current_user.profile_picture = filename

        db.session.commit()
        flash('Your settings have been updated!', 'success')
        return redirect(url_for('routes.settings'))

    # Pre-fill the form fields with the current user's data
    form.username.data = current_user.username
    form.email.data = current_user.email
    form.bio.data = current_user.bio

    return render_template('settings.html', title='Account Settings', form=form)

@routes.route('/test_db')
def test_db():
    try:
        users = User.query.all()
        return jsonify({'users': [str(user) for user in users]}), 200  # A list of string representations of User objects
    except Exception as e:
        return str(e), 500

myflaskapp/templates/articles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>News Articles</title>
</head>
<body>
    <h1>News Articles</h1>
    <ul>
        {% for article in articles %}
            <li>
                <h2>{{ article.title }}</h2>
                <p>{{ article.posted_timestamp }}</p>
                <a href="{{ url_for('routes.get_article', article_id=article.id) }}">Read more</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

myflaskapp/templates/base.html
{% extends 'layout.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
  <h1>Profile</h1>

  <h2>{{ user.username }}</h2>
  <p>Email: {{ user.email }}</p>

  {% if user.profile_picture %}
    <img src="{{ url_for('static', filename='profile_pictures/' ~ user.profile_picture) }}" alt="Profile Picture">
  {% else %}
    <p>No profile picture available.</p>
  {% endif %}
{% endblock %}

myflaskapp/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home Page</title>
    <link rel="stylesheet" type="text/css" href="static/css/home.css">
    <style>
        body {
            background-color: lightblue;
        }
    </style>
</head>
<body>
    

    <!-- Create a div with the class "home" to apply your styles -->
    <div class="home">
        <h1>Welcome To Our News Aggregator!</h1> <!-- Change the text here -->
        {% include 'navbar.html' %}
    </div>
</body>
</html>

myflaskapp/templates/layout.html
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}"> -->

  <title>{{ title }}</title>
</head>
<body>
  <header>
    {% include 'navbar.html' %}
  </header>
  <main>
    {% block content %}
    <!-- The content of the child templates will be rendered here -->
    {% endblock %}
  </main>
  <footer>
    <!-- Footer goes here -->
  </footer>

  <!-- Optional JavaScript -->
  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/js/bootstrap.bundle.min.js"></script>

  <!-- Custom JavaScript -->
  <!-- <script src="{{ url_for('static', filename='js/main.js') }}"></script> -->
</body>
</html>

myflaskapp/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="POST">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" required>
        <input type="submit" value="Login">
    </form>
</body>
</html>

myflaskapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('routes.home') }}">News Aggregator</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.home') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.articles') }}">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.profile') }}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.login') }}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.register') }}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('routes.search') }}">Search</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

myflaskapp/templates/profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>Profile</h1>

  <h2>{{ user.username }}</h2>
  <p>Email: {{ user.email }}</p>

  {% if user.profile_picture %}
    <img src="{{ url_for('static', filename='profile_pictures/' ~ user.profile_picture) }}" alt="Profile Picture">
  {% else %}
    <p>No profile picture available.</p>
  {% endif %}
{% endblock %}

myflaskapp/templates/register.html
<!-- register.html -->
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

myflaskapp/templates/search.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h1>Search</h1>
    <form action="{{ url_for('routes.search') }}" method="POST">
      <div class="form-group">
        <input type="text" name="search_query" class="form-control" placeholder="Enter your search query">
      </div>
      <button type="submit" class="btn btn-primary">Search</button>
    </form>

    {% if search_results %}
      <h2>Search Results</h2>
      <ul class="list-group">
        {% for result in search_results %}
          <li class="list-group-item">{{ result.title }}</li>
        {% endfor %}
      </ul>
      <!-- Pagination links can be added here -->
    {% endif %}
  </div>
{% endblock %}

myflaskapp/templates/settings.html
{% extends 'base.html' %}

{% block content %}
  <h1>Account Settings</h1>

  <form method="POST" action="{{ url_for('routes.update_settings') }}" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <div class="form-group">
      <label for="username">Username</label>
      {{ form.username(class="form-control") }}
    </div>

    <div class="form-group">
      <label for="email">Email</label>
      {{ form.email(class="form-control") }}
    </div>

    <div class="form-group">
      <label for="new_password">New Password</label>
      {{ form.new_password(class="form-control") }}
    </div>

    <div class="form-group">
      <label for="confirm_password">Confirm New Password</label>
      {{ form.confirm_password(class="form-control") }}
    </div>

    <div class="form-group">
      <label for="bio">Bio</label>
      {{ form.bio(class="form-control") }}
    </div>

    <div class="form-group">
      <label for="profile_picture">Profile Picture</label>
      {{ form.profile_picture(class="form-control-file") }}
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
  </form>
{% endblock %}

myflaskapp/templates/submit_article.html
<!DOCTYPE html>
<html>
<head>
    <title>Submit Article</title>
</head>
<body>
    <form method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=30) }}
        </p>
        <p>
            {{ form.link.label }}<br>
            {{ form.link(size=30) }}
        </p>
        <p>
            {{ form.description.label }}<br>
            {{ form.description(cols=30, rows=4) }}
        </p>
        <p>
            {{ form.category.label }}<br>
            {{ form.category(size=30) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
</body>
</html>

myflaskapp/templates/update_profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update Profile</h1>
  <form method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.bio.label(class="form-control-label") }}
      {{ form.bio(class="form-control") }}
    </div>

    <div class="form-group">
      {{ form.profile_picture.label(class="form-control-label") }}
      {{ form.profile_picture(class="form-control-file") }}
    </div>

    <div class="form-group">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>
{% endblock %}